### ISSUE TITLE
Locust SSL verification

### ISSUE THREAD

**Issue by MONTATICH** [GoogleCloudPlatform/distributed-load-testing-using-kubernetes#15]
I get this failure 
"SSLError(SSLError(SSLError(1, '_ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'),),)"
I don't want to verify SSL certificate! How can I change that ?

**Comment by viglesiasce** [comment]
The following issue provides the solution:
https://github.com/locustio/locust/issues/300

**Comment by MONTATICH** [comment]
sorry I don't know much about python
so I should modify tasks.py to either

class MetricsTaskSet(TaskSet):
    _deviceid = None

    def on_start(self):
        self._deviceid = str(uuid.uuid4())
        self.client.verify = False
OR

import uuid

from datetime import datetime
from locust import HttpLocust, TaskSet, task


class MetricsTaskSet(TaskSet):
    _deviceid = None

    def on_start(self):
        self._deviceid = str(uuid.uuid4())

    @task(1)
    def login(self):
        self.client.post(
            '/login', {"deviceid": self._deviceid})

    @task(999)
    def post_metrics(self):
        self.client.post(
            "/metrics", {"deviceid": self._deviceid, "timestamp": datetime.now()})
    
     self.client.post(url, name=name, data=data, verify=False)


class MetricsLocust(HttpLocust):
    task_set = MetricsTaskSet
