### ISSUE TITLE
CrashLoopBackOff for days

### ISSUE THREAD

**Issue by faizalkassamalisc** [GoogleCloudPlatform/distributed-load-testing-using-kubernetes#25]
@crcsmnky @evandbrown @erictune @feczo
This tutorial has potential but appears to be busted.  Can you please get it working again?

$ kubectl get pods -l name=locust,role=master
NAME                  READY     STATUS             RESTARTS   AGE
locust-master-fdppf   0/1       CrashLoopBackOff   6          6m

**Comment by viglesiasce** [comment]
Hey @faizalkassamalisc!

Apologies for that. The images were originally pushed with a registry version that is now disabled. I have re-uploaded them and all thing seem to be working as expected.

I have also made a few patches in #26.

**Comment by faizalkassamalisc** [comment]
Thank you!
